# Generated by Django 5.0.12 on 2025-03-02 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('current_balance', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitcoin_addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('timestamp', models.DateTimeField()),
                ('confirmations', models.IntegerField(default=0)),
                ('is_sending', models.BooleanField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.bitcoinaddress')),
            ],
        ),
    ]
