# Generated by Django 5.0.12 on 2025-03-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoinaddress',
            name='transaction_count',
            field=models.IntegerField(default=0),
        ),
    ]
