# Generated by Django 5.0.12 on 2025-03-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_bitcoinaddress_transaction_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoinaddress',
            name='last_fetched_page',
            field=models.IntegerField(default=0, help_text='Last page of transactions fetched'),
        ),
    ]
